# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06701dc6b7d780151f85e46d4b04ba7e003441512fc8d82d30072fbb79049f778fe22324e3a236b6f73a95d4e0c77b7a9115bd58031679f96cbf38c7ff6d1473

test:
  secret_key_base: a1073deffae5d668bc00f65a493e343223ef87a873be8fc533f72db74859a4109e774b6f63dc81387c32e31a5110002e5724e8606ff77baa64ae51b216dae2ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
